version: '3'

volumes:
  postgres_data: {}

services:
  web:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && yarn install && bundle exec rails s -b '0.0.0.0' -p 3000"
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
