default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db

development:
  <<: *default
  database: todoista_development 

test:
  <<: *default
  database: todoista_test 

production:
  <<: *default
  database: todoista_production
