default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  password:
  database: todoista_development 

test:
  <<: *default
  database: todoista_test 
  password:

production:
  <<: *default
  database: todoista_production
  username: todoista
  password: <%= Rails.application.credentials.production[:TODOISTA_DATABASE_PASSWORD] %>
  host: <%= Rails.application.credentials.production[:TODOISTA_DATABASE_HOST] %>
  port: <%= Rails.application.credentials.production[:TODOISTA_DATABASE_PORT] %>
